version: '3.8'
services:
  cache:
    image: redis:7.0.7-alpine3.17
    restart: unless-stopped

  social-backend:
    build: ./social-backend
    ports:
      - "8000:8000"
    # while loop is needed to postpone Django start until DB start
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate; python3 manage.py initadmin; uwsgi --ini /application/uwsgi.ini'
    # Command for BDD tests
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate; python3 manage.py initadmin; python3 manage.py behave'
    restart: unless-stopped
    depends_on:
      - cache
      - db

  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_admin
      - POSTGRES_PASSWORD=S0m3Passw0rd
      - POSTGRES_DB=social
    restart: unless-stopped
