version: '3.8'
services:
  cache:
    image: redis:7.0.6-alpine3.17
    restart: always

  social-backend:
    build: ./social-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - cache
      - db

  db:
    image: postgres:13.9-alpine3.17
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_admin
      - POSTGRES_PASSWORD=S0m3Passw0rd
      - POSTGRES_DB=social
    restart: unless-stopped
